default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instaclone_development

test:
  <<: *default
  database: instaclone_test
  host: <%= ENV['PG_HOST'] %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

production:
  <<: *default
  database: instaclone_production
  username: instaclone
  password: <%= ENV["INSTACLONE_DATABASE_PASSWORD"] %>
